apiVersion: v1
kind: Service
metadata:
  name: readylive-service
spec:
  selector:
    app: readylive
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: readylive-deployment
  labels:
    app: readylive
spec:
  replicas: 3
  selector:
    matchLabels:
      app: readylive
  template:
    metadata:
      labels:
        app: readylive
    spec:
      containers:
      - name: readylive
        image: adamwu/readylive:2.2
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /api/ready
            port: 80
            httpHeaders:
            - name: Custom-Header
              value: Awesome
          initialDelaySeconds: 5
          periodSeconds: 5